---
name: Build Project
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
        with:
          fetch-depth: 1
          show-progress: "false"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes build-essential libx11-dev libxcb1-dev libxau-dev libxdmcp-dev gzip

      - name: Build project
        run: make

      - name: Verify binary
        run: |
          test -f xwinfocus && echo "✅ Build succeeded" || (echo "❌ Build failed" && exit 1)
