name: Release

on:
  workflow_run:
    workflows:
      - "Build and Test"
    branches:
      - main
    types:
      - completed

concurrency:
  group: release-${{ github.event.workflow_run.id }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      PROG: xwinfocus
      OIDC_ISSUER: https://token.actions.githubusercontent.com
      NFPM_URL: https://github.com/goreleaser/nfpm
      NFPM_VERSION: 2.43.1
      DIST: dist

    permissions:
      actions: read
      contents: write
      id-token: write

    steps:
      - name: Download artifact from the triggering Build run
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # 5.0.0
        with:
          name: ${{ env.PROG }}
          run-id: ${{ github.event.workflow_run.id }}
          path: ${{ env.DIST }}
          github-token: ${{ github.token }}

      - name: Get version
        id: version
        run: |
          set -o pipefail
          chmod +x ${DIST}/${PROG}
          ${DIST}/${PROG} --version | \
            awk '{ printf("version=%s\n", $2) }' | \
            tee --append "${GITHUB_OUTPUT}"

      - name: Install Cosign
        uses: sigstore/cosign-installer@d58896d6a1865668819e1d91763c7751a165e159 # 3.9.2
        with:
          cosign-release: v2.5.3

      - name: Download nFPM checksums
        id: checksums
        env:
          FILE: checksums.txt
        run: |
          curl --fail --show-error --silent --location --remote-name \
            ${NFPM_URL}/releases/download/v${NFPM_VERSION}/${FILE}
          echo "file=${FILE}" >>"${GITHUB_OUTPUT}"

      - name: Verify nFPM checksums
        run: |
          cosign verify-blob \
            --certificate-identity ${NFPM_URL}/.github/workflows/release.yml@refs/tags/v${NFPM_VERSION} \
            --certificate-oidc-issuer ${OIDC_ISSUER} \
            --signature ${NFPM_URL}/releases/download/v${NFPM_VERSION}/${{ steps.checksums.outputs.file }}.sig \
            --cert ${NFPM_URL}/releases/download/v${NFPM_VERSION}/${{ steps.checksums.outputs.file }}.pem \
            ${{ steps.checksums.outputs.file }}

      - name: Download nFPM
        id: nfpm
        env:
          FILE: nfpm_${{ env.NFPM_VERSION }}_amd64.deb
        run: |
          curl --fail --show-error --silent --location --remote-name \
            ${NFPM_URL}/releases/download/v${NFPM_VERSION}/${FILE}
          echo "file=${FILE}" >>"${GITHUB_OUTPUT}"

      - name: Verify nFPM
        run: sha256sum --ignore-missing --check ${{ steps.checksums.outputs.file }}

      - name: Install nFPM
        run: sudo dpkg --no-triggers --install ${{ steps.nfpm.outputs.file }}

      - name: Create packages
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          old_dir="$(pwd)"
          cd ${DIST}
          for pkg in apk archlinux deb ipk rpm; do
            nfpm package --packager "${pkg}"
          done
          rm --force -- LICENSE ${PROG} ${PROG}.1.gz nfpm.yaml
          cd "${old_dir}"

      - name: Create and sign checksums
        id: checksum
        env:
          CHECKSUM_FILE: CHECKSUM.sha256
          COSIGN_EXPERIMENTAL: 1
        run: |
          old_dir="$(pwd)"
          cd ${DIST}
          find . -type f -print0 |
            sort --zero-terminated |
            xargs --null --max-args=1 basename |
            xargs ${CHECKSUM_FILE##*.}sum > ../${CHECKSUM_FILE}
          mv --force --verbose ../${CHECKSUM_FILE} .
          cosign sign-blob --yes ${CHECKSUM_FILE} \
            --output-signature ${CHECKSUM_FILE}.sig \
            --output-certificate ${CHECKSUM_FILE}.pem
          cd "${old_dir}"
          echo "file=${CHECKSUM_FILE}" >>"${GITHUB_OUTPUT}"
          echo "sig_file=${CHECKSUM_FILE}.sig" >>"${GITHUB_OUTPUT}"
          echo "pem_file=${CHECKSUM_FILE}.pem" >>"${GITHUB_OUTPUT}"

      - name: Get certificate identity
        id: certificate_identity
        run: |
          echo "url=${GITHUB_SERVER_URL}/${GITHUB_WORKFLOW_REF}" | tee --append "${GITHUB_OUTPUT}"

      - name: Verify checksums
        run: |
          cosign verify-blob \
            --certificate-identity ${{ steps.certificate_identity.outputs.url }} \
            --certificate-oidc-issuer ${OIDC_ISSUER} \
            --certificate ${DIST}/${{ steps.checksum.outputs.pem_file }} \
            --signature ${DIST}/${{ steps.checksum.outputs.sig_file }} \
            ${DIST}/${{ steps.checksum.outputs.file }}

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          target_commitish: ${{ github.event.workflow_run.head_sha }}
          generate_release_notes: true
          files: |
            ${{ env.DIST }}/${{ steps.checksum.outputs.file }}
            ${{ env.DIST }}/${{ steps.checksum.outputs.sig_file }}
            ${{ env.DIST }}/${{ steps.checksum.outputs.pem_file }}
            ${{ env.DIST }}/${{ env.PROG }}-${{ steps.version.outputs.version }}*-x86_64.pkg.tar.zst
            ${{ env.DIST }}/${{ env.PROG }}-${{ steps.version.outputs.version }}*.x86_64.rpm
            ${{ env.DIST }}/${{ env.PROG }}_${{ steps.version.outputs.version }}_amd64.deb
            ${{ env.DIST }}/${{ env.PROG }}_${{ steps.version.outputs.version }}_x86_64.apk
            ${{ env.DIST }}/${{ env.PROG }}_${{ steps.version.outputs.version }}_x86_64.ipk
